VpcCidr="10.0.0.0/16"
PublicSubnet1Cidr="10.0.0.0/18"
PublicSubnet2Cidr="10.0.64.0/18"
PrivateSubnet1Cidr="10.0.128.0/18"
PrivateSubnet2Cidr="10.0.192.0/18"
S3BucketName="belong-coding-challenge"
ImageId="ami-07b5c2e394fccab6e"
InstanceType="t2.micro"
SSHKeyName="httpd-access-key"